Mile-Writings/Mile-Client

- .babelrc
- package.json
- src/App.tsx
- src/main.tsx
- src/styles/emotion.d.ts
- src/styles/theme.ts
- tsconfig.json
- vite.config.ts
- yarn.lock
closes #15 
- vite.config 파일에 babel설정을 해주어야한다.
- theme를 사용하려면 d.ts파일로 theme 타입을 지정해주어야한다. 
- 
-
> [Init/#15] emotion settings

- src/App.tsx
- src/pages/main/components/Manual.tsx
closed #58
- 메뉴얼 타이틀 배치에 살짝 트러블을 겪었는데, 타이틀을 포함해서 메뉴얼의 가로 크기에 맞게 width를 설정해주고 그 안에서 flex-start를 해주면 되는 걸 알게 되었어요
-
- 후에 div 태그를 img 태그로 변경하여 이미지로 바꿀 예정입니다
> [Feat/#58] 메뉴얼

- src/Router.tsx
- src/pages/postPage/components/Editor.tsx
- src/pages/postPage/components/editor.css
> [Feat/#72] 에디터 뷰 제목 필드 추가

- src/assets/svgs/index.tsx
- src/pages/groupFeed/GroupFeed.tsx
- src/pages/main/components/Carousel.tsx
- src/pages/main/style/slick-theme.css
> [ fix/#97] slick 화살표 에러

- src/assets/svgs/index.tsx
- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/carousel/Carousel.tsx
- src/pages/groupFeed/carousel/CarouselContainer.tsx
- src/pages/groupFeed/components/GroupInfoBox.tsx
- src/pages/groupFeed/components/MakeGroupBtn.tsx
- src/pages/groupFeed/hooks/queries.ts
- src/pages/main/components/Carousel.tsx
> [ Fix/#114 ] merge error

- src/components/commons/LogInOutBtn.tsx
- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/apis/fetchGroupFeed.ts
- src/pages/groupFeed/carousel/Carousel.tsx
- src/pages/groupFeed/carousel/EachArticle.tsx
- src/pages/groupFeed/components/CuriousArticle.tsx
- src/pages/groupFeed/hooks/queries.ts
> [ Feat/#111 ] 글감별 글 리스트 API GET

- src/pages/main/components/Carousel.tsx
- src/pages/main/components/GroupContent.tsx
> [Fix/#139] 캐러셀 이미지 수정

- src/pages/postDetail/PostDetail.tsx
closed #149 
- div에 dangerouslySetInnerHTML속성 적용하면 html태그 적용 가능
-
> feat: dangerouslySetInnerHTML 적용

- src/pages/main/styles/slick-theme.css
closed #157 
- 경로문제였다.
- 기존 코드에서는 상대경로로 경로를 지정해줬었는데, 절대경로로 지정하니까 해결할 수 있었다!
- 왜 그런지는 더 알아볼 예정
-
> [Fix/#157] svg 절대경로

- src/pages/groupFeed/hooks/queries.ts
> [ fix/#159 ]  topicId 없을때는 요청 안쏘게

- src/pages/postDetail/apis/fetchCommentList.ts
- src/pages/postDetail/components/Comment.tsx
- src/pages/postDetail/hooks/queries.ts
> [ Fix/#182 ]error handling 403

- src/pages/postDetail/apis/fetchCuriousInfo.ts
- src/pages/postDetail/components/CuriousBtn.tsx
- src/pages/postDetail/hooks/queries.ts
> [ Fix/#190 ] 궁금해요 403 에러 handling

- src/pages/main/styles/slick-theme.css
> [ fix/#192 ] main arrow css 모임 arrow 안 덮게

- src/pages/Error/Error.tsx
- src/pages/Loading/Loading.tsx
- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/carousel/Carousel.tsx
- src/pages/groupFeed/components/CuriousArticle.tsx
- src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
- src/pages/main/components/FaqDropdown.tsx
- src/pages/postDetail/PostDetail.tsx
> [ Feat/#196 ] 로딩스피너 적용 및 에러페이지 라우팅 수정

- src/pages/groupFeed/carousel/Carousel.tsx
- src/pages/groupFeed/components/CuriousArticle.tsx
- src/pages/groupFeed/components/GroupFeedHeader.tsx
- src/pages/main/components/MainHeader.tsx
- src/pages/postDetail/components/CommentItem.tsx
- src/pages/postDetail/components/CuriousBtn.tsx
- src/pages/postPage/PostPage.tsx
> [ Fix/#199 ] 모임페이지 qa

- src/pages/groupFeed/components/GroupFeedHeader.tsx
- src/pages/main/components/MainHeader.tsx
- src/pages/postDetail/PostDetail.tsx
- src/pages/postPage/apis/editPutContent.ts
- src/pages/postPage/components/editor.css
> [Fix/#203] header routing

- src/pages/postDetail/components/CommentItem.tsx
> fix/#203: 삭제에 커서

- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/components/GroupSideHeader.tsx
- src/pages/postPage/PostPage.tsx
> fix/#210 : qa

- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/components/GroupSideHeader.tsx
- src/pages/postDetail/components/CommentItem.tsx
- src/pages/postPage/PostPage.tsx
> Develop to main

- src/assets/svgs/index.tsx
- src/pages/postPage/components/TipTap.tsx
closes #237 
- 딱히 없고 [이전 PR](https://github.com/Mile-Writings/Mile-Client/pull/235)과 같은 로직으로 구현했슴니다.
- PR 쪼개는 중 잘했쥬 ?
- 237 브랜치 커밋만 반영하려고 base 브랜치 변경해두었습니다. 머지할 때 확인하기~
-
https://github.com/Mile-Writings/Mile-Client/assets/109661444/bd3b9bac-b279-46a1-a7fb-801794dba491
> [Refactor/#237] 에디터 툴바 글자 색상 변경 뷰 커스텀

- src/components/commons/Modal.tsx
closes #278 
```tsx
const handleOutSideClick = () => {
if (isModalOpen) {
setModalBgClickActive(true);
preventScroll(); // 스크롤 방지 함수 적용
}
if (modalBgClickActive) {
closeModalHandler();
setModalBgClickActive(false);
}
};
```
- 모달이 열린 경우 preventScroll 함수 호출해주었습니다. 영상으로 찍으려 했으나 티가 안나서... 코드라도 남겨봅니다!
-
> [Fix/#278] 공통 모달 스크롤 방지 함수 적용

- src/pages/groupInvite/components/UserInfoInput.tsx
closes #328 
- 하나 추가해서 없어요~
- 하나 추가해서 없어요~
https://github.com/Mile-Writings/Mile-Client/assets/109661444/fdf170ba-229b-43b5-b67e-0597dc12bd05
> [Fix/#328] 모임 초대 페이지 2차 스프린트 QA

- package.json
- src/pages/groupFeed/carousel/Carousel.tsx
- src/pages/postDetail/PostDetail.tsx
- src/pages/postPage/PostPage.tsx
- src/pages/postPage/components/TipTap.tsx
- src/pages/postPage/components/tiptap.css
- yarn.lock
closes #327 
- 글 제출하기 버튼을 누를 때 한 번 함수가 실행되고, 모달이 열릴 때 제출하는 함수가 한 번 더 실행되고 있더라구요 ! 그래서 모달이 열릴 때 함수가 실행되는 거 지워두었습니다!
- sticky까지 해결하고 피알 날리려고 했는데 잘 해결이 안되어서 우선 이것부터 머지하면 될 것 같슴다!
- 없어요오
https://github.com/Mile-Writings/Mile-Client/assets/109661444/231ed8e4-3905-48c8-920d-d400b720f66b
> [Fix/#327] 에디터 글 제출 두 번 되는 이슈 해결

- src/pages/groupInvite/GroupInvite.tsx
closed #342 
```tsx
} else if (status === 401) {
navigate(`/login`);
}
```
- status 값에 따라 처리해주는 부분에서 조건문 하나 더 추가해줬습니다.
-
https://github.com/Mile-Writings/Mile-Client/assets/96781926/b1476929-f15c-4e7e-a902-38ef322360d3
> [Feat/#342] 초대링크 로그아웃일 때 로그인 페이지로 라우팅

- src/pages/groupFeed/carousel/EachArticle.tsx
> loading 경로 수정

- src/components/commons/Header.tsx
- src/pages/groupFeed/apis/fetchGroupFeed.ts
- src/pages/login/apis/loginService.ts
> hotfix: login redirect 리퀘스트 바디 수정

- src/mocks/handler.ts
- src/pages/admin/AddEditTopicModal.tsx
- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/apis/fetchGroupFeed.ts
- src/pages/groupFeed/hooks/queries.ts
closed #355 
- api 연결했고, 글감 설명 선택으로 받게 로직 변경햇슴다
- 
-
> [Feat/#355] 공개모임 여부 api 연결

- src/pages/groupFeed/carousel/Carousel.tsx
- src/pages/groupFeed/carousel/slick-theme.css
- src/pages/groupFeed/components/CuriousProfile.tsx
- src/pages/postDetail/components/CommentInputBox.tsx
- src/pages/postDetail/components/CommentItem.tsx
closed #352 
#336
- pre-wrap 속성값은 pre 속성값과 동일하게 연속된 띄어쓰기와 들여쓰기, 줄바꿈을 있는 그대로 보존한다
- 캐러셀 화살표 진짜 많이 고민했는데 끝까지 안되길래 important 박았어요
https://github.com/Mile-Writings/Mile-Client/assets/93575538/45138171-fb11-44e9-9fa9-664c003691f4
https://github.com/Mile-Writings/Mile-Client/assets/93575538/d522fea5-dab2-406c-a3a4-19c6300f5bf8
> [Feat/#352] 댓글 뷰 변경사항 반영 & 캐러셀 화살표 disable

- src/pages/groupInvite/apis/fetchWriterNameConflict.ts
- src/pages/groupInvite/components/GroupInfo.tsx
- src/pages/groupInvite/components/UserInfoInput.tsx
- src/pages/groupInvite/hooks/queries.ts
- src/utils/apis/axios.ts
closes #371 
- 조건부 처리 다시했어욤
- 우리 지금 dev아니라 기본 base로 api 날린다고 하는데 client도 devBaseUrl로 넣어져있길래 baseUrl로 수정해두었습니다 ~
```typescript
const baseUrl = import.meta.env.VITE_BASE_URL;
const devBaseUrl = import.meta.env.VITE_DEV_BASE_URL;
export const client = axios.create({
baseURL: `${baseUrl}`,
headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
});
export const devClient = axios.create({
baseURL: `${devBaseUrl}`,
headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
});
```
-
- 8자이내+중복확인 
https://github.com/user-attachments/assets/403300a3-72f2-4ae6-9f79-5e2497ec7a68
- 중복확인+중복된필명
https://github.com/user-attachments/assets/01ed38df-65bc-47ed-bb13-e985ced8a170
> [Fix/#372] 8자이내+중복확인 , 중복확인+중복된필명 같이뜨는 부분 해결

- .eslintrc.json
- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/apis/fetchGroupFeed.ts
- src/pages/groupFeed/hooks/queries.ts
- src/pages/groupInvite/GroupInvite.tsx
- src/pages/postDetail/PostDetail.tsx
- src/utils/apis/axios.ts
> [Fix/#387] 권한관련 에러, 권한에 의한 접근 처리

- src/pages/main/components/Introduction.tsx
- src/pages/postPage/apis/fetchTempSaveFlag.ts
> [ Hotfix/#397 ] 임시저장 api 인증된 axios로 요청하기]

- src/pages/main/components/CarouselContent.tsx
> [hotfix/#404] 캐러셀 본문과 이미지 간 gap 추가

- src/pages/groupInvite/GroupInvite.tsx
> [Hotfix/#409] 글모임 초대페이지 - 존재하지 않는 글모임 40010,40014에 대한 에러처리

- src/pages/groupInvite/GroupInvite.tsx
> [ Hotfix/#409 ] group invite400error handling (to develop)

- src/pages/createGroupSuccess/CreateGroupSuccess.tsx
closes #421 
- Margin-top 속성 하나 추가했슴다
- 없
이전
수정 후
> [design/#421] 글모임생성페이지 마진값 이상한 거 수정 

- src/constants/commentErrorMessage.ts
- src/pages/admin/apis/fetchAdminData.ts
- src/pages/admin/hooks/queries.ts
- src/pages/createGroup/hooks/queries.ts
- src/pages/groupInvite/hooks/queries.ts
- src/pages/postDetail/hooks/queries.ts
- src/pages/postPage/hooks/queries.ts
closed #417
- 빌드 에러납니다!!! 남다은이 한거가틈 내가 고쳐보라다가 useDeleteGroup이 아예 통으로 날라간거같아서 일단 냅뒀어요 다은이가 함 봐봐 
- 댓글 관련에서는 에러메시지를 '댓글을 입력해주세요'로 띄웠는데 포스팅의 경우에는 어떤 필드가 비어있는지 몰라서 '요청값, 빈값' 이라는 워딩이 불가피하게 들어갔는데요. 클라단에서 일단 토스트로 친절하게 요청값들에 대한 내용을 띄워주고 그럼에도 불구하고 모종의 이유로 서버에 요청이 갔을때는 저러한 워딩은 어쩔 수 없다는 생각이 들었습니다... 댓글도 사실 비어있으면 submit버튼 비활성화, 최대길이도 지정해놔서 요청갈 일은 매우 특이한 케이스일거같아요
- 
-완료한것들 캡쳐 떠왔어용
40010도 에러페이지로 라우팅 시켰습니다
미완인것들!!
-api가 무슨 api인지 안보여서 알려주시면 감사하겠습니다
-어떻게 처리할까요
1) 메인페이지로 아무말 없이 보내버린다
2) 비정상적인 접근입니다. 라고 말하고 보내버린다
3)에러페이지로 보내버린다
> [Feat/#416] 400handling

- src/pages/postPage/components/DropDown.tsx
- src/pages/postPage/components/ImageUpload.tsx
- src/pages/postPage/components/TipTap.tsx
#430 
- 간단한 변경이여서 없습니다.
- 간단한 변경이여서 없습니다! 
https://github.com/user-attachments/assets/38b725a2-2553-4dc3-8d97-1688e6726462
> [ Fix/#430 ] editor페이지 toolbar sticky 적용

- src/App.tsx
- src/components/commons/Button.tsx
- src/constants/errorText.ts
- src/pages/groupInvite/components/GroupInfo.tsx
- src/pages/postDetail/PostDetail.tsx
- src/pages/postDetail/apis/createPostCurious.ts
- src/pages/postDetail/apis/deleteCurious.ts
- src/pages/postDetail/components/CuriousBtn.tsx
- src/pages/postDetail/hooks/queries.ts
- src/styles/GlobalStyle.tsx
- src/utils/apis/axios.ts
#415 
`(variables: TVariables) => Promise<TContext | void> | TContext | void` (optional)
**onMutate함수는 mutation 함수가 실행되기 전에 호출되며, mutation 함수가 받는 것과 동일한 `variables`가 전달됩니다. 이 함수는 mutation이 성공할 것이라고 기대하며 리소스에 대해 낙관적 업데이트를 수행하는 데 유용합니다.**
- 이 함수에서 반환된 값은 뮤테이션이 실패한 경우 `onError` 및 `onSettled` 함수에 전달되며, 낙관적 업데이트를 되돌리는(롤백하는) 데 유용하게 사용할 수 있습니다.
**존재하는 쿼리의 캐시된 데이터를 가져오는 비동기 함수**
- 쿼리가 존재하지 않으면 `undefined` 를 return하고 option으로는 쿼리키를 넣어줘야합니다.
- return값으론 `TQueryFnData | undefined`
**쿼리에 캐싱된 데이터를 즉시 업데이트할 때 사용할 수 있는 `동기 함수`**
- 쿼리가 존재하지 않으면 쿼리를 생성합니다.
- gcTime 내에 쿼리 훅에 의해 사용되지 않으면 gc에 의해 메모리에서 제거합니다.
- 여러 쿼리를 한 번에 업데이트하고 쿼리키를 부분적으로 일치시키려면 setQueriesData사용
**setQuery와 fetchQuery의 차이점** 
- setQuery는 동기적이고 이미 동기적으로 사용할 수 있는 데이터라고 가정할 때 사용
- fetchQuery는 비동기적으로 데이터를 가져와야할 때 사용 …
> [Refactor/#415] 궁금해요 버튼 optimistic update(낙관적 업데이트) UX개선

- src/pages/createGroup/components/CreateGroupInfo.tsx
closes #435 
- 아무리 봐도 가로 스크롤이 생길 부분이 없어서 ..... 컴포넌트 하나하나 지우면서 언놈인가 찾아봤더니 
얘더라라구여 ...
width: fit-content 추가해두었습니다 ...
- 없
전
https://github.com/user-attachments/assets/29e854ad-6365-45d0-9c74-750211707c20
후
https://github.com/user-attachments/assets/17244107-6cc3-45a3-b6ac-efd25a9d2740
> [design/#435] 글 모임 생성 페이지 가로 스크롤 추가

- index.html
- src/App.tsx
- src/pages/admin/components/RenderAdminContent.tsx
- src/pages/createGroup/CreateGroup.tsx
- src/pages/createGroup/apis/postGroup.ts
- src/pages/createGroup/hooks/queries.ts
> [ Hotfix/#441 ] v5 머지 이후 qa (글모임생성 버튼 크기 / 페이지 이탈 모달 겹쳐서 뜨는 이슈 / 메타태그 수정)

- src/pages/createGroup/hooks/queries.ts
- src/pages/groupFeed/GroupFeed.tsx
- src/utils/apis/axios.ts
> [ Hotfix/#447 ] hotfix main merge용 PR - 글모임생성 api 반영

- src/pages/groupInvite/apis/createGroupMemberJoin.ts
- src/pages/groupInvite/hooks/queries.ts
- src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
> [ Hotfix/#449 ] hotfix main merge용 PR - 글모임가입 api 반영

- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/apis/fetchGroupFeed.ts
- src/pages/groupFeed/components/GroupTodayWriteStyle.tsx
- yarn.lock
> [fix/#455] 글감 데이터 자리 수정

- src/styles/GlobalStyle.ts
> [ hotfix ] 에디터 볼드, 기울기, 밑줄 globalStyle 반영

- src/components/commons/Footer.tsx
- src/pages/main/Main.tsx
- src/pages/main/components/CarouselContent.tsx
- src/pages/main/components/FaqDropdown.tsx
- src/pages/main/components/GroupCarousel.tsx
- src/pages/main/components/Manual.tsx
- src/styles/theme.ts
#474 
- 
-
https://github.com/user-attachments/assets/f704267b-33f7-4e17-af08-faab6f7bceb8
> [ Feat/#474 ] 메인페이지 반응형 뷰 변경사항 반영

- src/pages/login/Login.tsx
- src/styles/emotion.d.ts
- src/styles/theme.ts
closed #503 
- 마일 반응형 끝났다아아 🎉
- 없습니다 
https://github.com/user-attachments/assets/f23dfc21-91c9-4f31-b663-c5dd7cfd425c
> [Feat/#503] 로그인 반응형 뷰 구현

- src/components/commons/Header.tsx
- src/components/commons/MyMobileSidebar.tsx
> [fix/#507] 햄버거바 에러

- src/utils/allPostParsing.ts
- src/utils/getPostDetailParsingMetatg.ts
- vite.config.ts
> [ Feat/#500 ] dynamic og Meta tag 추가하기

- package.json
- vite.config.ts
> [ Feat/#500 ] dynamic og meta tag prerender 성공 

- vercel.json
> [ Feat/#500 ] dynamic og image - vercel path routing setting 수정 

- index.html
> feat: 일반 페이지 og태그 원복

- src/utils/allPostParsing.ts
- vite.config.ts
> [ Feat/#500 ] meta tag 중복 삭제 및 api url env활용 

- vite.config.ts
> fix: og tag url env 수정

- vite.config.ts
> [ Feat/#500 ] 주석제거 및 og:url env로 추가

- src/pages/groupInvite/components/UserInfoInput.tsx
- src/pages/groupJoinCongrats/GroupJoinCongrats.tsx
closes #525 
- 없
- 없
https://github.com/user-attachments/assets/2dc6c68c-f470-4681-b6aa-1c9eab753d88
> [Fix/#525] 글모임초대페이지 QA

- src/components/commons/Header.tsx
- src/pages/admin/components/EditGroupInfo.tsx
- src/pages/admin/components/MemberItem.tsx
- src/pages/admin/components/MemberManage.tsx
- src/pages/admin/components/RenderAdminContent.tsx
- src/utils/PageNumber.tsx
closed #523 
- 기존 flex로 헤더들 정렬했던 걸 grid로 변경했습니다.
- 없습니다 !
https://github.com/user-attachments/assets/655ca0d5-0a1e-46a5-af8a-ac674ef08184
> [Feat/#523] 관리자 페이지 QA 해결

- src/pages/groupFeed/GroupFeed.tsx
- src/pages/groupFeed/carousel/EachArticle.tsx
- src/pages/groupFeed/components/CuriousArticle.tsx
- src/pages/groupFeed/components/CuriousProfile.tsx
- src/pages/groupFeed/components/EditProfileModal.tsx
- src/pages/groupFeed/components/GroupMobileInfo.tsx
> [Fix/#521] 모임페이지 QA

- src/pages/error/Error.tsx
closed #521 
- 없
-없
https://github.com/user-attachments/assets/bc976a85-21b8-4ce1-a949-2551773a59d0
> [feat/#521] 에러페이지 반응형

- src/pages/main/Main.tsx
- src/pages/main/components/GroupCarousel.tsx
- src/pages/main/components/Introduction.tsx
- src/pages/main/components/Manual.tsx
> [ Fix/#522 ] 메인페이지 QA반영

- src/components/commons/Button.tsx
- src/pages/postPage/components/TipTap.tsx
- src/pages/postPage/components/TopicDropDown.tsx
- src/pages/postPage/components/tiptap.css
closes #520 
- 크롬에서는 툴바의 가로 스크롤 영역에서 margin-right가 안씹히는데 사파리에서는 씹히길래 툴바 마지막 요소에 :after 가상 선택자 추가해서 해결해두었습니다
- [하위에디터바가 내려오는 스타일 적용할 때 오류] 이슈 제외한 PR입니다~
-
> [ Fix/#520 ] 에디터 페이지 QA 반영

- src/pages/groupFeed/components/GroupMobileInfo.tsx
- src/pages/groupFeed/components/GroupSideHeader.tsx
> [fix] 모임페이지 글자수 수정 및 글자 정렬 qa

- public/mockServiceWorker.js
- src/assets/svgs/index.tsx
- src/constants/defaultImgUrl.ts
- src/constants/footerLink.ts
- src/pages/main/Main.tsx
- src/pages/main/components/CarouselContent.tsx
- src/pages/main/components/GroupCarousel.tsx
- src/pages/main/styles/slick-theme.css
- src/pages/postPage/constants/editorDefaultImg.ts
> [ Fix/#547] design QA

- src/assets/svgs/index.tsx
- src/pages/groupFeed/components/CuriousArticle.tsx
- src/pages/groupFeed/components/MyGroupDropDown.tsx
> [HotFix] qa
