.stylelintrc
src/styles/GlobalStyle.tsx
src/styles/theme.ts
yarn.lock

closes #30 
https://unnamedwritings.notion.site/stylelint-30189afd098b407388ab6f0bb1d9c8af?pvs=4
-

[Fix/#30]stylelint conflict

---

src/assets/svgs/index.tsx
src/components/commons/Footer.tsx
src/components/commons/Header.tsx
src/pages/groupFeed/GroupTodayWriteStyle.tsx
src/pages/groupFeed/carousel/Carousel.tsx
src/pages/groupFeed/carousel/EachArticle.tsx

[fix/#53] svgConvention 맞추기

---

src/pages/groupFeed/GroupFeed.tsx
src/pages/groupFeed/apis/fetchGroupFeed.ts
src/pages/groupFeed/components/CuriousProfile.tsx
src/pages/groupFeed/components/GroupFeedHeader.tsx
src/pages/groupFeed/hooks/queries.ts

closed #99 
- 다은이 라우팅할 때 모임에 대한 권한 확인 API GET에서 에러가 생겼었는데 제 문제였더라고요?ㅎ...
문제 : 500에러 뜸. 
해결 : accessToken이 없을 때에는 요청을 보내면 안됨. 쿼리훅으로 accessToken을 prop로 보내고, 그걸 받아서 enabled 설정을 해줬습니다
```typescript
const { data, isLoading, isError, error } = useQuery({
queryKey: [QUERY_KEY_GROUPFEED.getGroupFeedAuth, groupId],
queryFn: () => fetchGroupFeedAuth(groupId),
enabled: !!accessToken,
});
```
이렇게 설정하면 useQuery 훅이 accessToken이 존재할 때만 실행되도록 설정됨!!
-
case1) 궁금한 작가가 없을 때
case2) 궁금한 작가가 1명 있을 때
case3) 궁금한 작가가 2명 있을 때

[Feat/#99] 궁금해요 TOP 2 작가 API GET

---

src/assets/svgs/index.tsx
src/pages/postPage/components/TipTap.tsx

closes #239 
- 역시나 딱히 없고 [이전 PR](https://github.com/Mile-Writings/Mile-Client/pull/235)과 같은 로직으로 구현했슴니다.
- 역시나 PR 쪼개는 중 잘했쥬 ?
- 239 브랜치 커밋만 반영하려고 base 브랜치 변경해두었습니다. 머지할 때 확인하기~
```typescript
const TextColorList = styled.div<{ $isFontColorOpen: boolean }>`
position: absolute;
top: 2.9rem;
display: ${({ $isFontColorOpen }) => ($isFontColorOpen ? 'flex' : 'none')};
flex-direction: column;
gap: 0.6rem;
align-items: center;
justify-content: flex-start;
width: 11.6rem;
padding: 1rem;
background-color: ${({ theme }) => theme.colors.white};
border: 1px solid ${({ theme }) => theme.colors.gray50};
border-radius: 10px;
`;
const TextColorBgList = styled.div<{ $isFontBgColorOpen: boolean }>`
position: absolute;
top: 2.9rem;
display: ${({ $isFontBgColorOpen }) => ($isFontBgColorOpen ? 'flex' : …
```

[Refactor/#239] 에디터 툴바 글자 배경 색상 변경 뷰 커스텀

---

src/pages/groupFeed/components/GroupFeedHeader.tsx
src/pages/login/RedirectLogin.tsx
src/pages/login/hooks/useLoginService.ts
src/pages/main/components/Carousel.tsx
src/pages/main/components/MainHeader.tsx
src/pages/postDetail/PostDetail.tsx

closes #242 
-   window.history.forward(); 써져있는 페이지로는 뒤로가기 불가
- 헤더 같은 기능으로 두개가 똑같이 있고 컴포넌트명이 헷갈리게 되어있어서 리팩토링이 필요할 것 같습니다 !
https://github.com/Mile-Writings/Mile-Client/assets/81609304/40e6fa28-fda3-4b38-bf3b-ce9461b5121e

[Fix/#242] login routing to before

---

src/components/commons/Modal.tsx

closes #262 
- Modal 컴포넌트에서 modalContent={`가입 완료 시 필명 변경이 불가합니다. \n계속 하시겠습니까?`}와 같이 props를 전달해줬으나 위와 같이 줄바꿈 처리가 적용되지 않았습니다.
**해결**
```
white-space: pre-line;
```
- 모달의 내용이 있는 스타일 컴포넌트에서 위의 속성을 추가해주어 해결할 수 있었습니다. 위 속성을 추가해주고 `<br>`혹은 `\n`을 사용해서 줄바꿈 처리를 해주면 됩니다.
- `pre-line` 속성값은 줄바꿈 문자만 있는 그대로 처리하고 연속되는 띄어쓰기와 들여쓰기는 모두 띄어쓰기 한 번으로 처리하는 속성입니다.
<br />
---
두 가지 모달이 색이 칠해져 있는 버튼이 달랐는데, 색이 칠해져있는 버튼에 초점을 두어 해당 버튼이 사용자가 누르도록 유도하는 버튼이라고 판단했습니다. 그래서 컴포넌트명도 `NegativeModal`, `PositiveModal`로 정했습니다.
- `아니오` 버튼에 색이 칠해져 있는 컴포넌트가 `NegativeModal`과 `예`를 유도하는 `PositiveModal`로 나누어 제작했습니다. 그리고 모달의 버튼을 `ModalButton`이라는 컴포넌트로 나눴습니다.
`NegativeModal`, `PositiveModal`의 props들은 다음과 같습니다.
```tsx
interface modalContentPropTypes {
modalContent: string;
onClick: () => void; // `예` 버튼을 눌렀을 때 동작하는 함수
setIsVisible?: …
```

[Feat/#262] 공통 모달 구현

---

src/components/commons/Modal.tsx
src/hooks/useModal.tsx

closes #278 
모달의 상태를 관리하면서 **모달을 열고 닫는** 상태 관리 코드가 중복되는 걸 발견해서 이를 커스텀 훅으로 분리해서 관리했습니다.
```tsx
const useModal = () => {
const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
const handleShowModal = () => {
setIsModalOpen(true);
};
const handleCloseModal = () => {
setIsModalOpen(false);
};
return {
isModalOpen,
setIsModalOpen,
handleShowModal,
handleCloseModal,
};
};
```
---
<br />
테스트를 위해 로그인 페이지에서 로그인 버튼을 누를 때 모달이 뜨게 했고, 아니오 -> 원래 페이지, 예 -> 메인 페이지로 핸들링 되는 PositiveModal을 불러온 모습입니다. 
(아직 스크롤 방지 함수를 적용하지 않은 상태입니다!)
https://github.com/Mile-Writings/Mile-Client/assets/96781926/8b0e43b2-abc4-417c-b72e-3c248ba8deca
- 로그인 페이지에서는 다음 코드와 같이 useModal로부터 핸들러 함수와 모달의 현재 상태를 가져오고, 핸들러가 필요한 부분에 onClick을 적용하여 모달을 띄울 수 있습니다. 
- Modal 컴포넌트가 받는 인자 중 modalHandler에 '예' 버튼을 눌렀을 때 어떤 함수를 실행할지 전달해주면 …

[Fix/#278] 공통 모달 버그 수정

---

src/pages/admin/apis/fetchDeleteMember.ts
src/pages/admin/components/MemberManage.tsx

closes #308 
```tsx
const [deleteMemberId, setDeleteMemberId] = useState(-1);
... 생략
<ExpelBtn
onClick={() => {
setDeleteMemberId(writerNameId);
handleShowModal();
}}
... 생략
<NegativeModal
modalContent={
'삭제 시, 해당 멤버와 해당 멤버가 작성한\n글과 댓글도 모두 삭제됩니다. 계속 하시겠습니까?'
}
isModalOpen={isModalOpen}
modalHandler={() => {
deleteMember(deleteMemberId);
handleCloseModal();
}}
closeModalHandler={() => {
setDeleteMemberId(-1);
handleCloseModal();
}}
/>
```
- useState를 사용해서 삭제하기 버튼이 눌렸을 때 삭제될 멤버의 id를 저장해주고, 모달에서 인자로 전달해주어 저장된 멤버 id에 해당하는 멤버를 삭제해주었습니다.
-
https://github.com/Mile-Writings/Mile-Client/assets/96781926/8e554d9f-7b17-4260-ab33-4a1567e5142a

[Fix/#308] 멤버 삭제 모달 띄우기

---

src/pages/admin/Admin.tsx
src/pages/createGroupSuccess/CreateGroupSuccess.tsx
src/utils/copyLink.ts

closed #338
```tsx
export const copyLink = async (link: string) => {
try {
await navigator.clipboard.writeText(link);
alert('초대 링크가 복사되었습니다.');
} catch (err) {
console.error('클립보드 복사 실패:', err);
alert('클립보드 복사 실패');
}
};
```
- 다음과 같이 초대링크를 복사하는 로직을 `copyLink`함수로 빼줬습니다.
```tsx
const handleCopyLink = (invitationCode: string) => {
copyLink(`https://www.milewriting.com/group/${invitationCode}/groupInvite`);
};
```
- 위와 같이 핸들러 함수를 통해 유틸 함수를 불러와서 사용해줬습니다. 
- 유틸 함수 인자로 복사할 링크 전달해줬습니다.
-

[Fix/#338] 초대 링크 변경

---

src/pages/groupFeed/carousel/Carousel.tsx

closed #336 
- 기존 코드에서
https://github.com/Mile-Writings/Mile-Client/assets/93575538/a24bb027-b3d3-401a-8367-ee797200716f
이렇게 캐러셀이 맨 첫번쨰 슬라이드로 넘어오는 문제가 있었는데, Loading때문이었어요..
그게 실행될 동안 기존의 컴포넌트 트리가 언마운트되면서 로딩 후 다시 렌더링하려하면 초기상태로 돌아가는거죠
컴포넌트 전체를 언마운트 시키지 않는 방식으로 바꿨습니당~
-

[fix/#336] 캐러셀 새로고침 방지

---

src/pages/admin/apis/fetchMemberInfo.ts
src/pages/admin/components/MemberManage.tsx

closed #357 
- 알게 된 부분은 딱히 없고 서버에서 넘겨주는 `isOwner`값이 true인 경우 삭제하기 버튼 대신 텍스트로 대체해줬습니다.
- 텍스트의 경우 버튼 기능을 하지 않아서 button 태그가 아닌 span 태그를 사용해주었고 cursor default로 설정해주었습니다 !
-

[Feat] 글 모임 장인 경우 멤버 삭제 불가

---

src/pages/postDetail/PostDetail.tsx
src/pages/postDetail/apis/fetchPostDetail.ts

closed #361 
- 현재 바뀐 뷰에서 날짜가 2024년 6월 13일 15:59식으로 나와야 하는데 지금은 `24.06.13 15:59`식으로 서버에서 받아오고 있어서 이 부분 알맞게 보내달라고 요청한 상태입니다 !
- 위 부분 해결됐습니다 !
**작가 소개 띄우기**
```tsx
<WriterDesc>
{!postData?.writerInfo ? '아직 작가소개를 작성하지 않았어요' : postData?.writerInfo}
</WriterDesc>
```
삼항연산자 사용해서 작가소개 부분 코드 고쳤습니다 !
-

[Feat] 글 상세 페이지 디테일 정보 추가

---

src/pages/main/Main.tsx
src/pages/main/components/CarouselContent.tsx
src/pages/main/components/GroupCarousel.tsx
src/pages/main/components/Introduction.tsx
src/pages/main/components/Manual.tsx
src/utils/apis/axios.ts

closed #369 
- `이 모임에 대해서 더 궁금하신가요?` 부분을 다른 flex 영역으로 분리해주고 감싸고 있는 바깥 레이아웃에 gap을 줘서 해결했습니다
-

[Feat/#369] 마지막 캐러셀 슬라이드 이미지 영역 QA 수정

---

src/assets/svgs/editorThuminputIcnUnactive.svg
src/assets/svgs/index.tsx
src/pages/postPage/components/ImageUpload.tsx

closes #380 
-  svg의 Rect값에 stroke를 먹여야하는데 ,, 어떻게 하지 하다가 Path랑 똑같이 적용해봤는데 되더라구요 ? 신기함
-
https://github.com/user-attachments/assets/ddeffb93-fee6-4444-844b-4a0d4a804b21

[Fix/#380] 에디터 페이지 썸네일 추가 버튼 호버값, active값 수정, 썸네일 Border-radius 재적용

---

src/pages/postPage/PostPage.tsx
src/pages/postPage/hooks/queries.ts

closes #390 
```typescript
export const useTempSaveFlag = (
groupId: string,
tempSaveFlag: boolean,
): TempSaveFlagQueryResult => {
const { data, isLoading, isError, error } = useQuery({
queryKey: [QUERY_KEY_POST.getTempSaveFlag, groupId, tempSaveFlag],
queryFn: () => fetchTempSaveFlag(groupId),
✅ enabled: !!tempSaveFlag, ✅
});
const isTemporaryPostExist = data && data?.data?.isTemporaryPostExist;
const tempPostId = data && data?.data?.postId;
return { isTemporaryPostExist, tempPostId, isLoading, isError, error };
};
```
임시저장 글이 있는지 없는지 여부에 따라 
이 모달을 띄워야해서 에디터 페이지에 접근하면 `임시저장 글 존재 여부 확인하는 api`를 쏘게 했었는데 그러다보니 수정하기로 들어온 경우에도 해당 api를 쏘더라구요
그래서 `enabled` 속성으로 수정하기로 들어왔을 경우가 아닌 경우 (**기존 글 작성 플로우로 들어온 경우**)에만 api 쏘도록 수정해두었습니다 !
- 없
- 기존 글 작성으로 들어왔을 경우 (현재재 권한이 있어도 401이 뜨는 이슈가 있긴 합니다만 .. 이 피알에선 …

[Hotfix/#390] 게시글 수정하기로 들어왔을 경우 임시저장 글 존재 여부 api 쏘지 않도록 수정

---

src/pages/groupInvite/GroupInvite.tsx
src/utils/apis/axios.ts

- document.referrer  속성은 페이지로 이동시키기 이전의 페이지 URI를 반환하는 속성입니다.  해당 페이지로 바로 접근했을시에는 빈 문자열을 반환합니다. 
- window.location 객체는 정말 다양한 속성으로 현재 페이지의 URL을 알아올 수 있는데. 저는 그중에서 pathname을 활용해서 이전페이지로 이동하는 로직을 구현했습니다. 
-

[ Hotfix/#409 ] group 초대페이지 에러 핸들링 수정 , 로그인 페이지에서 이전페이지 라우팅하는 기능 추가

---

src/pages/groupInvite/GroupInvite.tsx
src/utils/apis/axios.ts

- document.referrer  속성은 페이지로 이동시키기 이전의 페이지 URI를 반환하는 속성입니다.  해당 페이지로 바로 접근했을시에는 빈 문자열을 반환합니다. 
- window.location 객체는 정말 다양한 속성으로 현재 페이지의 URL을 알아올 수 있는데. 저는 그중에서 pathname을 활용해서 이전페이지로 이동하는 로직을 구현했습니다. 
-

[ Hotfix/#409] group invite error handling (to main)

---

src/utils/apis/axios.ts

closed #426 
```tsx
const originReq = err.config;
if (err.response && err.response.status === 401 && !originReq._retry) {
if (err.response.data.status === 40102) {
originReq._retry = true;
try {
const { data } = await refresh();
const newToken = data.data.accessToken;
authClient.defaults.headers['Authorization'] = `Bearer ${newToken}`;
originReq.headers.Authorization = `Bearer ${newToken}`;
localStorage.setItem('accessToken', newToken);
return authClient.request(originReq);
} catch (err) {
console.error(err);
localStorage.removeItem('accessToken');
window.location.href = '/login';
}
}
```
- 인터셉터 관련 코드에서 `_retry` 플래그가 같은 요청을 중복으로 재시도하지 않도록 하기 위해 작성된 코드임을 알게 됐습니다.
- 토큰이 만료됨을 확인하고 리프래시 토큰을 받아오기 위해 작성된 코드임을 알게 되었고, 500대 에러는 서버에서 발생한 에러이기 때문에 해당 조건문을 추가하지 않았습니다.
-

[Feat/#426] 500대 에러 처리

---

index.html
src/App.tsx
src/pages/admin/components/RenderAdminContent.tsx
src/pages/createGroup/CreateGroup.tsx

closes #441 
- 글모임생성 -> 방장 정보 입력할 때 버튼 크기 지정해서 수정해두었습니다.
- 관리자페이지 , 글모임가입페이지에서 모든 정보 입력 후 완료 모달이 뜬 후에, 다음 페이지로 이동할 때 페이지 이탈 모달이 활성화 되는 이슈를 확인했습니다.
- setIgnoerBlocker라고 페이지 이탈 모달을 비활성화 할 수 있는 상태를 이전에 만들어뒀어서 해당 부분 위에 로직들에도 추가해두었습니다.
- 메타태그 관련 작업이 잘 작동하지 않아서 확인해본 결과 App.tsx내부에 있더라구요. index.html 안으로 이동해줬고, 이미지도 github issue활용해서 변환한 url로 넣어두었습니다. 
-

[ Hotfix/#441 ] v5 머지 이후 qa (글모임생성 버튼 크기 / 페이지 이탈 모달 겹쳐서 뜨는 이슈 / 메타태그 수정)

---

index.html
src/pages/createGroup/CreateGroup.tsx
src/pages/createGroup/apis/postGroup.ts
src/pages/createGroup/hooks/queries.ts

closes #441 
- response로 오는 데이터 타입이 이상하게 지정되어있더라구요 수정했습니다 
- 메타태그의 이미지 크기 지정해줬습니다
-

[ Hotfix/#441 ] v5머지 이후 QA - 글모임생성 완료 후 그룹아이디 안 받아와지는 거 수정

---

src/pages/createGroup/hooks/queries.ts
src/pages/groupFeed/GroupFeed.tsx
src/utils/apis/axios.ts

closes #447 
- 글모임 생성할 때 서버에서 응답으로 넘겨주는 데이터가 바뀐 것 같더라구요 ! 회의할 때 accessToken을 새로 발급해준다고 들었던 것 같아서 찾아보니 api가 변경 완료 되어있길래 반영했습니다.
- `usePostCreateGroup` api에서 onSuccess일 경우 localStorage의 accessToken을 변경해주고, authClient의 헤더도 최신화 시켜주도록 반영해두었습니다.
- 처음에는 localStorage.setItem을 해서 업데이트만 시켜줬는데, 이렇게하니까 글모임페이지에 들어갔을 때 필명과 소개글 정보가 받아와지지 않고 403 에러가 나더라구요. 새로고침을 하면 잘 받아와지는 것을 확인했습니다.
- 보니까 `usePostCreateGroup`의 응답값으로 새로운 토큰이 잘 넘어오긴 하지만, authClient의 헤더에 들어가있는 토큰 최신화 작업이 즉시 반영되지 않아서 이전 토큰으로 요청이 가는거더라구요
- 따라서 `onSuccess` 로직에 authClient 헤더 최신화 작업도 추가해주었습니다.
```typescript
// createGroup > queries.ts > usePostCreateGroup
onSuccess: (data) => {
queryClient.invalidateQueries({ queryKey: [QUERY_KEY_CREATE_GROUP.postCreateGroup] });
localStorage.setItem('accessToken', data.data.accessToken);
// authClient 헤더 최신화 …
```

[ Hotfix/#447 ] 글모임생성 변경된 api 반영 - accessToken 받아오는 로직 반영

---

src/pages/groupInvite/apis/createGroupMemberJoin.ts
src/pages/groupInvite/hooks/queries.ts
src/pages/groupJoinCongrats/GroupJoinCongrats.tsx

closes #449 
- 이전 피알과 같이, 글모임에 가입했을 때 토큰을 새로 발급해주도록 api가 변경되어있어서 반영했습니다
-

[ Hotfix/#449 ] 글 모임 초대 페이지 변경된 api 반영

---

src/pages/admin/components/EachTopic.tsx

closes #463 
- 글감 설명이 두 줄일 경우 글감 태그가 글감 높이에 맞도록 정렬되게 수정했어요
-
[이전]
[이후]
- 글감 소개 한 줄
-글감 소개 두 줄

[design/#463] 글감태그 정렬 수정

---

src/pages/groupFeed/carousel/Carousel.tsx
src/pages/groupFeed/carousel/EachArticle.tsx
src/pages/postDetail/PostDetail.tsx

closes #465 
- word-break: keep-all 
영문, 숫자, 특수문자 띄어쓰기 없이 썼을 경우 줄바꿈 안됨, 한글 강제 줄바꿈 됨
- word-break: break-all
영문, 숫자, 특수문자 띄어쓰기 없이 썼을 경우 줄바꿈 됨. 영문 단어 단위로 줄바꿈됨. 한글 강제 줄바꿈 됨.
-
[이전]
[이후]

[design/#465] 글상세페이지 숫자, 영문, 특수문자 줄바꿈 안됨 이슈

---

.stylelintrc
package.json
src/App.tsx
src/components/commons/Footer.tsx
src/components/commons/Responsive/Responsive.tsx
src/components/commons/Responsive/ResponsiveProvider.tsx
src/components/commons/Responsive/context.ts
src/pages/main/Main.tsx
src/pages/main/components/CarouselContent.tsx
src/pages/main/components/DailyKeyword.tsx
src/pages/main/components/FaqDropdown.tsx
src/pages/main/components/GroupCarousel.tsx
src/pages/main/components/Introduction.tsx
src/pages/main/components/Manual.tsx
src/pages/main/components/OnBoarding.tsx
src/pages/main/components/skeletons/CarouselSkeleton.tsx
src/pages/main/styles/slick-theme.css
src/pages/main/styles/slick.css
src/styles/mediaQuery.ts
yarn.lock

#474 
- Responsive 컴포넌트의 children 컴포넌트에서 width: 100% 같은 값을 사용하면 children 컴포넌트의 부모컴포넌트는 Responsive이기때문에 의도한 대로 동작하지 않는다 그럴 때 asChild props를 통해 Slot을 활용하면 아래와 같이 원래 컴포넌트의 직계 자식 컴포넌트 처럼 활용하여 props뿐만 아니라 style속성도 inherit 받을 수 있다.
- 슬롯 활용 전후 html 태그 차이 확인
Slot 활용 전
Slot 활용 후
- 
- 없습니다!

[Feat/#474] responsive basic setting & main page 임시 responsive 뷰 적용

---

package.json
vite.config.ts
yarn.lock

[ Feat/#500 ] 동정 OG image 배포 에러 해결 ( 버전 맞추기, port 변경, legacy 버전 이슈 해결로 빌드 성공_

---

package.json
src/App.tsx
src/routers/RouteTracker.tsx
src/routers/routeChangeTracker.ts
yarn.lock

closed #543 
- `react-ga4` 라이브러리를 사용해주었습니다.
배포시 포함되어야하기 때문에 `dependencies`로 설치해주었어요
react의 경우 `SPA`구조이기 때문에 각 페이지의 html마다 코드를 주입해주는 방법을 사용하지 않고, `useLocation`을 사용해서 위치의 변경을 인식할 때마다 정보를 날려주는 방식으로 구현했습니다.
**RouteTracker.tsx**
```tsx
// 로컬일 경우 send하지 않음
useEffect(() => {
if (!window.location.href.includes('localhost')) {
ReactGA.initialize(import.meta.env.VITE_GOOGLE_ANALYTICS_ID);
setIsInitialized(true);
}
}, []);
// pathname과 정보를 날려줌
useEffect(() => {
if (isInitialized) {
ReactGA.set({ page: location.pathname });
ReactGA.send('pageview');
}
}, [isInitialized, location]);
```
원래는 유틸 함수처럼 만들고 App.tsx 상위에서 호출했으나, 구글링해보니 BrowseRouter 외부에서 호출된다는 에러가 뜬다고 해서 RouteTracker 라는 컴포넌트를 만들고 RouteProvider 하위에서 호출해주었습니다.
```tsx
<Suspense fallback={<Loading />}>
<RouterProvider router={router} /> …
```

[Feat] Google Analytics 세팅

---

src/App.tsx
src/components/commons/Layout.tsx
src/routers/PrivateRoute.tsx

[Fix/#543] RouteTracker 호출 위치 변경

---

src/pages/main/components/CarouselContent.tsx
src/pages/main/components/GroupCarousel.tsx

closes #550 
- 메인페이지 글모임 글리스트 모바일일 경우 가로 스크롤 생기는 이슈 수정
- 기존에 데스크탑일 경우 사용하고 있는 캐러셀 컴포넌트를 사용하려다가 모바일일 경우 overflow : scroll 적용하는 방향으로 수정했어요. 
- 나중에 제대로 적용하려면 [slick-slider에 전달하는 setting에 responsive 속성 추가해서 수정해봐도 괜찮을듯합니다.](https://react-slick.neostack.com/docs/example/responsive)
-
https://github.com/user-attachments/assets/599d219d-0387-4e4f-9ff9-5a05e06c5f9c

[fix/#550] 메인페이지 글모임 글 리스트 반응형 캐러셀 적용

---

src/pages/admin/components/EditGroupInfo.tsx
src/pages/createGroup/components/CreateGroupInfo.tsx
src/pages/groupFeed/GroupFeed.tsx
src/pages/postDetail/PostDetail.tsx
src/pages/postPage/components/ImageUpload.tsx

closed #553 
(https://www.notion.so/milewriting/1aacdb08633f8005b86acb59358a6dd2?pvs=4)
이거 햇습니다.
- 
-
전1
후1
전2
후2

[Fix/#553] 이미지 비율 수정
